In [1]:
import pandas as pd
import sys
from Bio.Seq import Seq
import subprocess

In [2]:
gene_db = pd.read_table("feature_db_part1.txt")

In [3]:
gene_db.head()

,gene_id,chrom,start,end,number_of_cds,gene_name,name_alias
0,FBgn0085506,211000022278760,562,879,2,CG40635,FBan0040635
1,FBgn0259817,211000022279188,1449,2180,3,SteXh:CG42398,RR41752;CG42398;StellateXh:CG42398
2,FBgn0085692,211000022280328,7386,9527,4,CG41561,FBan0041561
3,FBgn0031208,2L,7529,9484,6,CG11023,NaN
4,FBgn0002121,2L,9839,21376,48,l(2)gl,Lgl;lgl;lethal giant larvae;lethal giant larve...

In [4]:
gene_db.head()

,gene_id,chrom,start,end,number_of_cds,gene_name,name_alias
0,FBgn0085506,211000022278760,562,879,2,CG40635,FBan0040635
1,FBgn0259817,211000022279188,1449,2180,3,SteXh:CG42398,RR41752;CG42398;StellateXh:CG42398
2,FBgn0085692,211000022280328,7386,9527,4,CG41561,FBan0041561
3,FBgn0031208,2L,7529,9484,6,CG11023,NaN
4,FBgn0002121,2L,9839,21376,48,l(2)gl,Lgl;lgl;lethal giant larvae;lethal giant larve...

In [5]:
gene_db.name_alias[gene_db.gene_id=="FBgn0002121"]

4    Lgl;lgl;lethal giant larvae;lethal giant larve...
Name: name_alias, dtype: object

In [6]:
cds_db = pd.read_table("feature_db_part2.txt")

In [7]:
cds_db

,CDS_name,CDS_loc,length,gene_name
0,Nep3-PA,"X:join(19963955..19964071,19964782..19964944,1...",2361,Nep3
1,CG9570-PA,X:20051456..20052088;,633,CG9570
2,Or19b-PA,"X:join(20094398..20095134,20095288..20095648,2...",1164,Or19b
3,CG15322-PB,"X:join(20133990..20134013,20135014..20135233,2...",2223,CG15322
4,Or19a-PB,"X:complement(join(20141819..20141884,20141938....",1164,Or19a
5,karr-PA,X:complement(20110183..20110476);,294,karr
6,fd19B-PA,X:complement(20091603..20092385);,783,fd19B
7,CG17003-PA,X:complement(20001103..20001966);,864,CG17003
8,CG12655-PA,"X:complement(join(19958500..19958900,19959301....",468,CG12655
9,CG33217-PA,"3L:join(23126208..23126400,23126717..23127251,...",2100,CG33217
10,Vps11-PA,3L:complement(23147895..23150387);,2493,Vps11
11,RpL10-PC,"3L:complement(join(23093714..23093878,23094684...",657,RpL10
12,G9a-PA,"X:join(246850..247596,248382..250238,250294..2...",4914,G9a
13,G9a-PB,"X:join(246850..247596,248382..250238,250294..2...",4974,G9a
14,cin-PB,"X:join(255794..255824,255881..256641,256762..2...",1806,cin
15,CG3777-PB,"X:join(343820..343833,346149..347707,348080..3...",2640,CG3777
16,CG12470-PA,X:308208..308795;,588,CG12470
17,Or1a-PA,"X:join(315123..315628,315775..316378,316489..3...",1179,Or1a
18,y-PA,"X:join(356680..356917,359617..361004);",1626,y
19,ac-PA,X:370094..370699;,606,ac
20,sc-PA,X:396177..397214;,1038,sc
21,l(1)sc-PA,X:409796..410569;,774,l(1)sc
22,ase-PA,X:460956..462416;,1461,ase
23,CG13373-PA,"X:join(477621..477931,478013..478076);",375,CG13373
24,CG13373-PB,"X:join(477147..477291,477607..477931,478013..4...",534,CG13373
25,CG32817-PA,"X:join(479644..479945,480030..480093);",366,CG32817
26,CG3176-PA,"X:join(482132..482433,482518..482581);",366,CG3176
27,CG3176-PB,X:482132..482437;,306,CG3176
28,CG3156-PA,"X:join(487990..488362,488422..488628,488874..4...",2079,CG3156
29,CG17778-PA,"X:join(495070..495117,495469..495804);",384,CG17778
...,...,...,...,...
22210,CG5126-PA,"2L:complement(join(1182495..1183471,1183529..1...",1368,CG5126
22211,Charon-PA,"2L:complement(join(1170793..1170956,1171030..1...",1575,Charon
22212,Plap-PA,"2L:complement(join(1167243..1167954,1168012..1...",2364,Plap
22213,CG5080-PB,"2L:complement(join(1160444..1161219,1161290..1...",1665,CG5080
22214,Tfb4-PA,"2L:complement(join(1149514..1149586,1149651..1...",900,Tfb4
22215,Iris-PA,2L:complement(1132478..1134073);,1596,Iris
22216,Pino-PB,"2L:complement(join(1115734..1115943,1116441..1...",750,Pino
22217,Pino-PA,"2L:complement(join(1115734..1115943,1116441..1...",516,Pino
22218,CG4629-PE,"2L:complement(join(1084019..1084836,1084894..1...",1713,CG4629
22219,S-PB,"2L:complement(join(1052038..1052265,1052331..1...",1794,S
22220,CG4375-PA,2L:complement(1026276..1026785);,510,CG4375
22221,CG2839-PA,2L:625663..628143;,2481,CG2839
22222,Hsp60B-PA,2L:728508..730454;,1947,Hsp60B
22223,GABA-B-R3-PA,"2L:join(753119..753730,754487..754630,755021.....",3918,GABA
22224,GABA-B-R3-PC,"2L:join(753119..753730,754487..754630,755021.....",1953,GABA
22225,GABA-B-R3-PH,"2L:join(753119..753730,754487..754630,755021.....",1353,GABA
22226,GABA-B-R3-PF,"2L:join(753119..753730,754487..754630,755021.....",1074,GABA
22227,CG12506-PA,2L:773595..773918;,324,CG12506
22228,CG13946-PA,2L:776542..776841;,300,CG13946
22229,CG13947-PA,2L:779204..779563;,360,CG13947
22230,Gr21a-PA,"2L:join(781297..782048,782124..782181,782238.....",1344,Gr21a
22231,CG3544-PA,2L:784421..786139;,1719,CG3544
22232,Nnf1b-PA,"2L:join(810646..810758,810809..811021,811089.....",615,Nnf1b
22233,Pex12-PA,2L:816083..816976;,894,Pex12
22234,Clp-PA,2L:820079..820969;,891,Clp
22235,dock-PA,"2L:join(829950..829971,830145..830349,830738.....",1233,dock
22236,dock-PB,"2L:join(829536..829971,830145..830349,830738.....",1647,dock
22237,kraken-PA,"2L:join(852936..853005,853192..853278,853545.....",996,kraken
22238,CG13949-PA,"2L:join(855550..855623,855687..855810,855868.....",438,CG13949
22239,CG13950-PA,"2L:join(860321..860409,860764..861357,861429.....",951,CG13950

In [8]:
def get_gene_record(identifier,by,source="feature_db_part1.txt"):
    gene_db = pd.read_table(source)
    if by == "gene_id":
        gene_id = identifier
        if sum(gene_db.gene_id==gene_id)<1:
            print ("Not found in our database")
            sys.exit()
        else:
            return gene_db[gene_db.gene_id==gene_id]
    else:
        gene_name = identifier
        if sum(gene_db.gene_name==gene_name)<1:
            print ("Not found in our database")
            sys.exit()
        else:
            return gene_db[gene_db.gene_name==gene_name]

In [9]:
def fa_parser(fh):
    seq_id = None
    seq=[]
    for line in fh:
        line=line.rstrip()
        if line.startswith(">"):
            if seq_id:
                yield(seq_id,"".join(seq))
            seq_id=line[1:]
            seq=[]
        else:
            seq.append(line)
    if seq_id: yield(seq_id,"".join(seq))

In [10]:
class Gene:
    def __init__(self,**kwargs):
        self.gene_id= kwargs.get("gene_id",-1)
        self.gene_name=kwargs.get("gene_name",-1)
        legal_arg=["gene_id","gene_name"]
        if not [i for i in kwargs.keys()][0] in legal_arg:
            raise ValueError("must init with gene_id or gene_name")
        else:
            if  self.gene_id != -1:
                record_df = get_gene_record(self.gene_id,by="gene_id")
                self.gene_name = [i for i in record_df.gene_name][0]
                self.record_df = record_df
                self.index = int([i for i in record_df.index][0])
            else:
                record_df = get_gene_record(self.gene_name,by="gene_name")
                self.gene_id = [i for i in record_df.gene_id][0]
                self.record_df = record_df
                self.index = int([i for i in record_df.index][0])
    def get_cds_record(self, source="feature_db_part2.txt"):
        cds_db = pd.read_table(source)
        cds_records = cds_db[cds_db.gene_name == self.gene_name]
        return cds_records
    
    def get_longest_cds(self, source ="feature_db_part2.txt"):
        cds_records = self.get_cds_record(source=source)
        index_longest_cds = cds_records.length.idxmax()
        return cds_records.loc[index_longest_cds,:]
    
    def get_neighbor_records(self,source="feature_db_part1.txt"):
        gene_db = pd.read_table(source)
        total_row =  gene_db.shape[0]
        row_index = self.index
        if row_index >9 and row_index < total_row-9:
            df_left = gene_db.iloc[row_index-10:row_index,:]
            df_right= gene_db.iloc[row_index+1:row_index+11,:]
            return([df_left,df_right])
        elif row_index <=9 :
            df_left= gene_db.iloc[0:row_index,:]
            df_right= gene_db.iloc[row_index+1:21,:]
            return([df_left,df_right])
        else:
            df_left=gene_db.iloc[total_row-21:row_index,:]
            df_right = gene_db.iloc[row_index+1:total_row+1,:]
            return ([df_left,df_right])
    def get_cds_fasta (self,fasta_source = "dmel-all-CDS-r6.26.fasta"):
        cds_name = self.get_longest_cds()["CDS_name"]
        with open(fasta_source) as fh:
            fasta_records = fa_parser(fh)
            for seq_id,seq in fasta_records:
                space_index = seq_id.index(" ")
                seq_name = seq_id[:space_index]
                if seq_name == cds_name:
                    return "\n".join([">"+seq_name,seq])
    def create_neighbor_fasta_file(self):
        left_nb = self.get_neighbor_records()[0]
        right_nb = self.get_neighbor_records()[1]
        gene_id_list = [i for i in left_nb.gene_id]+[i for i in right_nb.gene_id]
        with open (self.gene_id+"_neighbor_cds.fasta","w") as write_file:
            for gene in gene_id_list:
                gene_obj= Gene(gene_id=gene)
                fa = gene_obj.get_cds_fasta()
                cds_id,cds_seq = fa.split("\n")
                protein_seq = str(Seq(cds_seq).translate())
                write_file.write(cds_id)
                write_file.write("\n")
                write_file.write(protein_seq)
                write_file.write("\n")

In [106]:
def parse_blast_result(blast_handle):
    blast_records = NCBIXML.parse(blast_handle)
    def parse_one_record(blast_record):
        for alignment in blast_record.alignments:
            chrom_id= alignment.title.split()[0]
            hsps = alignment.hsps
            coordinate_list = []
            for hsp in hsps:
                coordinate_list.append((hsp.sbjct_start,hsp.sbjct_end))
            yield (chrom_id,coordinate_list)
    for blast_record in blast_records:
        yield(parse_one_record(blast_record))

In [111]:
test= next(parse_blast_result(result_handle))

In [115]:
next(test)

('scaffold_6540',
 [(29551577, 29552971),
  (29553046, 29553543),
  (26169810, 26171777),
  (1584251, 1584658),
  (1584723, 1584971),
  (1585319, 1585438),
  (1585042, 1585215),
  (26175648, 26177519),
  (26178781, 26180682),
  (9812633, 9813739),
  (33048794, 33050530),
  (9695013, 9695357),
  (9695450, 9695632),
  (1582121, 1583569),
  (33051111, 33053054),
  (26174745, 26175536),
  (33055111, 33056280),
  (29426393, 29427142),
  (9696707, 9697279),
  (9698189, 9698494),
  (29553845, 29554036)])

In [101]:
def hello():
    yield("12","ab")

In [103]:
a=hello()

In [19]:
from Bio.Blast import NCBIXML

In [110]:
result_handle = open("result.xml","r")

In [21]:
blast_records= NCBIXML.parse(result_handle)

In [23]:
blast_record=next(blast_records)

In [97]:
blast_record.alignments[0].hsps[0].sbjct_start

11391110

In [11]:
test=Gene(gene_name="Nep3")

In [87]:
test.create_neighbor_fasta_file()

In [60]:
with open("haha","w") as hah:
    hah.write(test.get_cds_fasta())

In [70]:
test.get_neighbor_records()[0]

,gene_id,chrom,start,end,number_of_cds,gene_name,name_alias
12959,FBgn0267043,X,19914482,19915281,2,CG45487,NaN
12960,FBgn0267044,X,19919641,19920435,2,CG45488,NaN
12961,FBgn0267045,X,19928416,19929178,2,CG45489,NaN
12962,FBgn0267046,X,19933541,19934294,2,CG45490,NaN
12963,FBgn0267047,X,19938232,19938994,2,CG45491,NaN
12964,FBgn0267048,X,19943357,19944147,2,CG45492,NaN
12965,FBgn0267049,X,19948079,19948873,2,CG45493,NaN
12966,FBgn0267050,X,19952814,19953608,2,CG45494,NaN
12967,FBgn0264309,X,19957548,19958342,2,CG43784,CR43784
12968,FBgn0031080,X,19958393,19959403,2,CG12655,NaN

In [71]:
[i for i in test.get_neighbor_records()[0].gene_id]+[i for i in test.get_neighbor_records()[1].gene_id]

['FBgn0267043',
 'FBgn0267044',
 'FBgn0267045',
 'FBgn0267046',
 'FBgn0267047',
 'FBgn0267048',
 'FBgn0267049',
 'FBgn0267050',
 'FBgn0264309',
 'FBgn0031080',
 'FBgn0031082',
 'FBgn0053517',
 'FBgn0031085',
 'FBgn0031086',
 'FBgn0062565',
 'FBgn0260871',
 'FBgn0040784',
 'FBgn0085360',
 'FBgn0031088',
 'FBgn0260873']

In [72]:
# LEFT FLANK
test.get_neighbor_records()[0]

,gene_id,chrom,start,end,number_of_cds,gene_name,name_alias
12959,FBgn0267043,X,19914482,19915281,2,CG45487,NaN
12960,FBgn0267044,X,19919641,19920435,2,CG45488,NaN
12961,FBgn0267045,X,19928416,19929178,2,CG45489,NaN
12962,FBgn0267046,X,19933541,19934294,2,CG45490,NaN
12963,FBgn0267047,X,19938232,19938994,2,CG45491,NaN
12964,FBgn0267048,X,19943357,19944147,2,CG45492,NaN
12965,FBgn0267049,X,19948079,19948873,2,CG45493,NaN
12966,FBgn0267050,X,19952814,19953608,2,CG45494,NaN
12967,FBgn0264309,X,19957548,19958342,2,CG43784,CR43784
12968,FBgn0031080,X,19958393,19959403,2,CG12655,NaN

In [73]:
# RIGHT FLANK
test.get_neighbor_records()[1]

,gene_id,chrom,start,end,number_of_cds,gene_name,name_alias
12970,FBgn0031082,X,20000968,20002096,1,CG17003,NaN
12971,FBgn0053517,X,20004680,20062706,27,Dop2R,FBgn0031083;FBgn0031084;FBgn0046542;FBgn004654...
12972,FBgn0031085,X,20051294,20052519,1,CG9570,NaN
12973,FBgn0031086,X,20091428,20092408,1,fd19B,Dmcg9571;fd19B;CG9571
12974,FBgn0062565,X,20094398,20095767,3,Or19b,FBgn0052825;CG32825;Odorant receptor-19b
12975,FBgn0260871,X,20096162,20096474,2,CG42581,NaN
12976,FBgn0040784,X,20110110,20110575,1,karr,CG15323
12977,FBgn0085360,X,20122453,20125271,3,CG34331,NaN
12978,FBgn0031088,X,20133579,20138878,10,CG15322,NaN
12979,FBgn0260873,X,20139793,20140170,1,CG42583,NaN

In [32]:
test.record_df

,gene_id,chrom,start,end,number_of_cds,gene_name,name_alias
12969,FBgn0031081,X,19961297,19969323,16,Nep3,dNEP3;CEC;CG9565;DmeNEP3;NEP3;nep3;neprilysin 3

In [ ]:
test.

In [36]:
toy_seq= Seq(test.get_cds_fasta().split("\n")[1])

In [42]:
protein_seq = toy_seq.translate()

In [46]:
str(protein_seq)

'MTRYKQTEFTEDDSSSIGGIQLNEATGHTGMQIRYHTARATWNWRSRNKTEKWLLITTFVMAITIFTLLIVLFTDGGSSDATKHVLHVQPHQKDCPSGNELPCLNKHCIFASSEILKSIDVTVDPCDDFYGYSCNQWIKNNPIPEGKSTWGTFGKLEQMNQLIIRNVLEKPAKSFKSDAERKAKVYYESCLDADEHMEKLGAKPMNDLLLQIGGWNVTKSGYNVANWTMGHTLKILHNKYNFNCLFGWAIGEDDKNSSRHVIQIDQGGLTLPTADYYNNKTDNHRKVLNEYIEYMTKVCVLLGANESDARAQMIGVINFEKKLANITIPLEDRRNEEAMYHPMQLRQLSKLAPFLNWTDHFDNAMQMVGRRVTDDEVVVVYAPDFLKNLSDIILKMEQTEEGKITLNNYLVWQAVRTLTSCLSKPFRDAYKGVRKALMGSDGGEEIWRYCVSDTNNVVGFAVGAIFVRQAFHGESKPAAEQMIAEIREAFKMNLQNLTWVDKQTREKAIEKANQISDMIGFPDYILDPVELDKKYAELNITPNAYFENNIQVAIYNLKSNLKRLDQPVNKTNWGMTPQTVNAYYTPTKNQIVFPAGILQTPFFDINNPKSLNFGAMGVVMGHELTHAFDDQGREYDKFGNINRWWDSKSIERFNEKSECIARQYSGYKMNGRTLNGKQTLGENIADNGGLKAAYHAYQRTKSDRDVDILKLPGLNLTHSQLFFVSFAQVWCSSTTDETNLLQMEKDPHSPSQFRVIGTLSNMKEFAEVFQCKPGKRMNPTEKCEVW*'

## Run blast locally

In [18]:
db_fasta="Dmojavensis-all-chromosome-r1.04.fasta"
subprocess.call(["makeblastdb","-in",db_fasta,"-dbtype","nucl","-parse_seqids"])

0

In [12]:
test.get_cds_fasta()[1]

'N'

In [17]:
subprocess.call(["tblastn","-query","test.fasta","-db","Dmojavensis-all-chromosome-r1.04.fasta",
                 "-evalue","1e-6","-outfmt","5","-out","result.xml"])

0